/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {8, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {18, 1, 1};

static const casadi_real casadi_zeros[10] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* f1tenth_expl_ode_fun:(i0[8],i1[2],i2[18])->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w01, w02, w03, w04, w05, w06, w08, w09, w10, w11, w12;
  casadi_real w13, w14, *w15=w+31;
  const casadi_real *cs, *wr00, *wr07;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[3] */
  w01 = wr00[3];
  /* #2: @2 = @0[2] */
  w02 = wr00[2];
  /* #3: @3 = cos(@2) */
  w03 = cos( w02 );
  /* #4: @4 = (@1*@3) */
  w04  = (w01*w03);
  /* #5: @5 = @0[4] */
  w05 = wr00[4];
  /* #6: @2 = sin(@2) */
  w02 = sin( w02 );
  /* #7: @6 = (@5*@2) */
  w06  = (w05*w02);
  /* #8: @4 = (@4-@6) */
  w04 -= w06;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #10: @2 = (@1*@2) */
  w02  = (w01*w02);
  /* #11: @3 = (@5*@3) */
  w03  = (w05*w03);
  /* #12: @2 = (@2+@3) */
  w02 += w03;
  /* #13: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #14: @2 = @0[5] */
  w02 = wr00[5];
  /* #15: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #16: @3 = 3.74 */
  w03 = 3.7400000000000002e+00;
  /* #17: @4 = @0[7] */
  w04 = wr00[7];
  /* #18: @7 = input[2][0] */
  wr07 = arg[2] ? arg[2] : casadi_zeros;
  /* #19: @6 = @7[8] */
  w06 = wr07[8];
  /* #20: @4 = (@4*@6) */
  w04 *= w06;
  /* #21: @6 = @7[9] */
  w06 = wr07[9];
  /* #22: @6 = (@6*@1) */
  w06 *= w01;
  /* #23: @4 = (@4-@6) */
  w04 -= w06;
  /* #24: @4 = (@3*@4) */
  w04  = (w03*w04);
  /* #25: @6 = @7[6] */
  w06 = wr07[6];
  /* #26: @4 = (@4-@6) */
  w04 -= w06;
  /* #27: @6 = @7[7] */
  w06 = wr07[7];
  /* #28: @6 = (@6*@1) */
  w06 *= w01;
  /* #29: @6 = (@6*@1) */
  w06 *= w01;
  /* #30: @4 = (@4-@6) */
  w04 -= w06;
  /* #31: @6 = @7[4] */
  w06 = wr07[4];
  /* #32: @8 = @7[2] */
  w08 = wr07[2];
  /* #33: @9 = @7[0] */
  w09 = wr07[0];
  /* #34: @10 = @0[6] */
  w10 = wr00[6];
  /* #35: @11 = 0.15875 */
  w11 = 1.5875000000000000e-01;
  /* #36: @12 = (@11*@2) */
  w12  = (w11*w02);
  /* #37: @12 = (@12+@5) */
  w12 += w05;
  /* #38: @13 = 1e-08 */
  w13 = 1.0000000000000000e-08;
  /* #39: @13 = (@13+@1) */
  w13 += w01;
  /* #40: @12 = atan2(@12,@13) */
  w12  = atan2(w12,w13);
  /* #41: @12 = (@10-@12) */
  w12  = (w10-w12);
  /* #42: @9 = (@9*@12) */
  w09 *= w12;
  /* #43: @9 = atan(@9) */
  w09 = atan( w09 );
  /* #44: @8 = (@8*@9) */
  w08 *= w09;
  /* #45: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #46: @6 = (@6*@8) */
  w06 *= w08;
  /* #47: @8 = sin(@10) */
  w08 = sin( w10 );
  /* #48: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #49: @4 = (@4-@8) */
  w04 -= w08;
  /* #50: @4 = (@4/@3) */
  w04 /= w03;
  /* #51: @8 = (@5*@2) */
  w08  = (w05*w02);
  /* #52: @4 = (@4+@8) */
  w04 += w08;
  /* #53: output[0][3] = @4 */
  if (res[0]) res[0][3] = w04;
  /* #54: @4 = @7[5] */
  w04 = wr07[5];
  /* #55: @8 = @7[3] */
  w08 = wr07[3];
  /* #56: @9 = @7[1] */
  w09 = wr07[1];
  /* #57: @12 = 0.17145 */
  w12 = 1.7144999999999999e-01;
  /* #58: @14 = (@12*@2) */
  w14  = (w12*w02);
  /* #59: @14 = (@14-@5) */
  w14 -= w05;
  /* #60: @14 = atan2(@14,@13) */
  w14  = atan2(w14,w13);
  /* #61: @9 = (@9*@14) */
  w09 *= w14;
  /* #62: @9 = atan(@9) */
  w09 = atan( w09 );
  /* #63: @8 = (@8*@9) */
  w08 *= w09;
  /* #64: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #65: @4 = (@4*@8) */
  w04 *= w08;
  /* #66: @10 = cos(@10) */
  w10 = cos( w10 );
  /* #67: @8 = (@6*@10) */
  w08  = (w06*w10);
  /* #68: @8 = (@4+@8) */
  w08  = (w04+w08);
  /* #69: @8 = (@8/@3) */
  w08 /= w03;
  /* #70: @1 = (@1*@2) */
  w01 *= w02;
  /* #71: @8 = (@8-@1) */
  w08 -= w01;
  /* #72: output[0][4] = @8 */
  if (res[0]) res[0][4] = w08;
  /* #73: @11 = (@11*@6) */
  w11 *= w06;
  /* #74: @11 = (@11*@10) */
  w11 *= w10;
  /* #75: @12 = (@12*@4) */
  w12 *= w04;
  /* #76: @11 = (@11-@12) */
  w11 -= w12;
  /* #77: @12 = 0.04712 */
  w12 = 4.7120000000000002e-02;
  /* #78: @11 = (@11/@12) */
  w11 /= w12;
  /* #79: output[0][5] = @11 */
  if (res[0]) res[0][5] = w11;
  /* #80: @15 = input[1][0] */
  casadi_copy(arg[1], 2, w15);
  /* #81: @11 = @15[0] */
  for (rr=(&w11), cs=w15+0; cs!=w15+1; cs+=1) *rr++ = *cs;
  /* #82: output[0][6] = @11 */
  if (res[0]) res[0][6] = w11;
  /* #83: @11 = @15[1] */
  for (rr=(&w11), cs=w15+1; cs!=w15+2; cs+=1) *rr++ = *cs;
  /* #84: output[0][7] = @11 */
  if (res[0]) res[0][7] = w11;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 33;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 33*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
