/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {8, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {18, 1, 1};
static const casadi_int casadi_s3[3] = {10, 1, 1};

static const casadi_real casadi_zeros[10] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* f1tenth_expl_vde_adj:(i0[8],i1[8],i2[2],i3[18])->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w00=w+0, w02, w03, w04, w06, w07, w08, w09, w10, w11, w12;
  casadi_real w13, w14, w15, w16, w17, w18, w20, w21, w22, w23, w24, w25;
  casadi_real w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, *w37=w+67;
  const casadi_real *cs, *wr01, *wr05, *wr19;
  /* #0: @0 = zeros(8x1) */
  casadi_clear(w00, 8);
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[6] */
  w02 = wr01[6];
  /* #3: @3 = sin(@2) */
  w03 = sin( w02 );
  /* #4: @4 = 0.15875 */
  w04 = 1.5875000000000000e-01;
  /* #5: @5 = input[3][0] */
  wr05 = arg[3] ? arg[3] : casadi_zeros;
  /* #6: @6 = @5[4] */
  w06 = wr05[4];
  /* #7: @7 = @5[2] */
  w07 = wr05[2];
  /* #8: @8 = @5[0] */
  w08 = wr05[0];
  /* #9: @9 = @1[5] */
  w09 = wr01[5];
  /* #10: @10 = (@4*@9) */
  w10  = (w04*w09);
  /* #11: @11 = @1[4] */
  w11 = wr01[4];
  /* #12: @10 = (@10+@11) */
  w10 += w11;
  /* #13: @12 = 1e-08 */
  w12 = 1.0000000000000000e-08;
  /* #14: @13 = @1[3] */
  w13 = wr01[3];
  /* #15: @12 = (@12+@13) */
  w12 += w13;
  /* #16: @14 = atan2(@10,@12) */
  w14  = atan2(w10,w12);
  /* #17: @14 = (@2-@14) */
  w14  = (w02-w14);
  /* #18: @14 = (@8*@14) */
  w14  = (w08*w14);
  /* #19: @15 = atan(@14) */
  w15 = atan( w14 );
  /* #20: @15 = (@7*@15) */
  w15  = (w07*w15);
  /* #21: @16 = sin(@15) */
  w16 = sin( w15 );
  /* #22: @16 = (@6*@16) */
  w16  = (w06*w16);
  /* #23: @17 = (@4*@16) */
  w17  = (w04*w16);
  /* #24: @18 = 21.2224 */
  w18 = 2.1222410865874362e+01;
  /* #25: @19 = input[1][0] */
  wr19 = arg[1] ? arg[1] : casadi_zeros;
  /* #26: {@20, @21, @22, @23, @24, @25, @26, @27} = vertsplit(@19) */
  w20 = wr19[0];
  w21 = wr19[1];
  w22 = wr19[2];
  w23 = wr19[3];
  w24 = wr19[4];
  w25 = wr19[5];
  w26 = wr19[6];
  w27 = wr19[7];
  /* #27: @18 = (@18*@25) */
  w18 *= w25;
  /* #28: @17 = (@17*@18) */
  w17 *= w18;
  /* #29: @17 = (@3*@17) */
  w17  = (w03*w17);
  /* #30: @17 = (-@17) */
  w17 = (- w17 );
  /* #31: (@0[6] += @17) */
  for (rr=w00+6, cs=(&w17); rr!=w00+7; rr+=1) *rr += *cs++;
  /* #32: @17 = (@13*@24) */
  w17  = (w13*w24);
  /* #33: @17 = (-@17) */
  w17 = (- w17 );
  /* #34: (@0[5] += @17) */
  for (rr=w00+5, cs=(&w17); rr!=w00+6; rr+=1) *rr += *cs++;
  /* #35: @17 = (@9*@24) */
  w17  = (w09*w24);
  /* #36: @17 = (-@17) */
  w17 = (- w17 );
  /* #37: (@0[3] += @17) */
  for (rr=w00+3, cs=(&w17); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #38: @17 = 0.26738 */
  w17 = 2.6737967914438499e-01;
  /* #39: @24 = (@17*@24) */
  w24  = (w17*w24);
  /* #40: @25 = (@16*@24) */
  w25  = (w16*w24);
  /* #41: @25 = (@3*@25) */
  w25  = (w03*w25);
  /* #42: @25 = (-@25) */
  w25 = (- w25 );
  /* #43: (@0[6] += @25) */
  for (rr=w00+6, cs=(&w25); rr!=w00+7; rr+=1) *rr += *cs++;
  /* #44: @25 = 0.17145 */
  w25 = 1.7144999999999999e-01;
  /* #45: @28 = (@25*@9) */
  w28  = (w25*w09);
  /* #46: @28 = (@28-@11) */
  w28 -= w11;
  /* #47: @29 = sq(@28) */
  w29 = casadi_sq( w28 );
  /* #48: @30 = sq(@12) */
  w30 = casadi_sq( w12 );
  /* #49: @29 = (@29+@30) */
  w29 += w30;
  /* #50: @31 = (@28/@29) */
  w31  = (w28/w29);
  /* #51: @32 = @5[1] */
  w32 = wr05[1];
  /* #52: @33 = @5[3] */
  w33 = wr05[3];
  /* #53: @28 = atan2(@28,@12) */
  w28  = atan2(w28,w12);
  /* #54: @28 = (@32*@28) */
  w28  = (w32*w28);
  /* #55: @34 = atan(@28) */
  w34 = atan( w28 );
  /* #56: @34 = (@33*@34) */
  w34  = (w33*w34);
  /* #57: @34 = cos(@34) */
  w34 = cos( w34 );
  /* #58: @35 = @5[5] */
  w35 = wr05[5];
  /* #59: @36 = (@25*@18) */
  w36  = (w25*w18);
  /* #60: @36 = (@24-@36) */
  w36  = (w24-w36);
  /* #61: @35 = (@35*@36) */
  w35 *= w36;
  /* #62: @34 = (@34*@35) */
  w34 *= w35;
  /* #63: @33 = (@33*@34) */
  w33 *= w34;
  /* #64: @34 = 1 */
  w34 = 1.;
  /* #65: @28 = sq(@28) */
  w28 = casadi_sq( w28 );
  /* #66: @28 = (@34+@28) */
  w28  = (w34+w28);
  /* #67: @33 = (@33/@28) */
  w33 /= w28;
  /* #68: @32 = (@32*@33) */
  w32 *= w33;
  /* #69: @31 = (@31*@32) */
  w31 *= w32;
  /* #70: @31 = (-@31) */
  w31 = (- w31 );
  /* #71: (@0[3] += @31) */
  for (rr=w00+3, cs=(&w31); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #72: @29 = (@12/@29) */
  w29  = (w12/w29);
  /* #73: @29 = (@29*@32) */
  w29 *= w32;
  /* #74: @32 = (-@29) */
  w32 = (- w29 );
  /* #75: (@0[4] += @32) */
  for (rr=w00+4, cs=(&w32); rr!=w00+5; rr+=1) *rr += *cs++;
  /* #76: @25 = (@25*@29) */
  w25 *= w29;
  /* #77: (@0[5] += @25) */
  for (rr=w00+5, cs=(&w25); rr!=w00+6; rr+=1) *rr += *cs++;
  /* #78: @25 = (@11*@23) */
  w25  = (w11*w23);
  /* #79: (@0[5] += @25) */
  for (rr=w00+5, cs=(&w25); rr!=w00+6; rr+=1) *rr += *cs++;
  /* #80: @9 = (@9*@23) */
  w09 *= w23;
  /* #81: (@0[4] += @9) */
  for (rr=w00+4, cs=(&w09); rr!=w00+5; rr+=1) *rr += *cs++;
  /* #82: @2 = cos(@2) */
  w02 = cos( w02 );
  /* #83: @17 = (@17*@23) */
  w17 *= w23;
  /* #84: @16 = (@16*@17) */
  w16 *= w17;
  /* #85: @16 = (@2*@16) */
  w16  = (w02*w16);
  /* #86: @16 = (-@16) */
  w16 = (- w16 );
  /* #87: (@0[6] += @16) */
  for (rr=w00+6, cs=(&w16); rr!=w00+7; rr+=1) *rr += *cs++;
  /* #88: @16 = sq(@10) */
  w16 = casadi_sq( w10 );
  /* #89: @16 = (@16+@30) */
  w16 += w30;
  /* #90: @10 = (@10/@16) */
  w10 /= w16;
  /* #91: @15 = cos(@15) */
  w15 = cos( w15 );
  /* #92: @18 = (@2*@18) */
  w18  = (w02*w18);
  /* #93: @18 = (@4*@18) */
  w18  = (w04*w18);
  /* #94: @2 = (@2*@24) */
  w02 *= w24;
  /* #95: @18 = (@18+@2) */
  w18 += w02;
  /* #96: @3 = (@3*@17) */
  w03 *= w17;
  /* #97: @18 = (@18-@3) */
  w18 -= w03;
  /* #98: @6 = (@6*@18) */
  w06 *= w18;
  /* #99: @15 = (@15*@6) */
  w15 *= w06;
  /* #100: @7 = (@7*@15) */
  w07 *= w15;
  /* #101: @14 = sq(@14) */
  w14 = casadi_sq( w14 );
  /* #102: @34 = (@34+@14) */
  w34 += w14;
  /* #103: @7 = (@7/@34) */
  w07 /= w34;
  /* #104: @8 = (@8*@7) */
  w08 *= w07;
  /* #105: @10 = (@10*@8) */
  w10 *= w08;
  /* #106: (@0[3] += @10) */
  for (rr=w00+3, cs=(&w10); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #107: @12 = (@12/@16) */
  w12 /= w16;
  /* #108: @12 = (@12*@8) */
  w12 *= w08;
  /* #109: @16 = (-@12) */
  w16 = (- w12 );
  /* #110: (@0[4] += @16) */
  for (rr=w00+4, cs=(&w16); rr!=w00+5; rr+=1) *rr += *cs++;
  /* #111: @4 = (@4*@12) */
  w04 *= w12;
  /* #112: @4 = (-@4) */
  w04 = (- w04 );
  /* #113: (@0[5] += @4) */
  for (rr=w00+5, cs=(&w04); rr!=w00+6; rr+=1) *rr += *cs++;
  /* #114: (@0[6] += @8) */
  for (rr=w00+6, cs=(&w08); rr!=w00+7; rr+=1) *rr += *cs++;
  /* #115: @8 = @5[7] */
  w08 = wr05[7];
  /* #116: @4 = (@8*@13) */
  w04  = (w08*w13);
  /* #117: @4 = (@4*@17) */
  w04 *= w17;
  /* #118: @4 = (-@4) */
  w04 = (- w04 );
  /* #119: (@0[3] += @4) */
  for (rr=w00+3, cs=(&w04); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #120: @4 = (@13*@17) */
  w04  = (w13*w17);
  /* #121: @8 = (@8*@4) */
  w08 *= w04;
  /* #122: @8 = (-@8) */
  w08 = (- w08 );
  /* #123: (@0[3] += @8) */
  for (rr=w00+3, cs=(&w08); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #124: @8 = @5[9] */
  w08 = wr05[9];
  /* #125: @4 = 3.74 */
  w04 = 3.7400000000000002e+00;
  /* #126: @4 = (@4*@17) */
  w04 *= w17;
  /* #127: @8 = (@8*@4) */
  w08 *= w04;
  /* #128: @8 = (-@8) */
  w08 = (- w08 );
  /* #129: (@0[3] += @8) */
  for (rr=w00+3, cs=(&w08); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #130: @8 = @5[8] */
  w08 = wr05[8];
  /* #131: @8 = (@8*@4) */
  w08 *= w04;
  /* #132: (@0[7] += @8) */
  for (rr=w00+7, cs=(&w08); rr!=w00+8; rr+=1) *rr += *cs++;
  /* #133: (@0[5] += @22) */
  for (rr=w00+5, cs=(&w22); rr!=w00+6; rr+=1) *rr += *cs++;
  /* #134: @22 = @1[2] */
  w22 = wr01[2];
  /* #135: @8 = sin(@22) */
  w08 = sin( w22 );
  /* #136: @4 = (@11*@21) */
  w04  = (w11*w21);
  /* #137: @4 = (@8*@4) */
  w04  = (w08*w04);
  /* #138: @4 = (-@4) */
  w04 = (- w04 );
  /* #139: (@0[2] += @4) */
  for (rr=w00+2, cs=(&w04); rr!=w00+3; rr+=1) *rr += *cs++;
  /* #140: @22 = cos(@22) */
  w22 = cos( w22 );
  /* #141: @4 = (@22*@21) */
  w04  = (w22*w21);
  /* #142: (@0[4] += @4) */
  for (rr=w00+4, cs=(&w04); rr!=w00+5; rr+=1) *rr += *cs++;
  /* #143: @4 = (@13*@21) */
  w04  = (w13*w21);
  /* #144: @4 = (@22*@4) */
  w04  = (w22*w04);
  /* #145: (@0[2] += @4) */
  for (rr=w00+2, cs=(&w04); rr!=w00+3; rr+=1) *rr += *cs++;
  /* #146: @21 = (@8*@21) */
  w21  = (w08*w21);
  /* #147: (@0[3] += @21) */
  for (rr=w00+3, cs=(&w21); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #148: @11 = (@11*@20) */
  w11 *= w20;
  /* #149: @11 = (@22*@11) */
  w11  = (w22*w11);
  /* #150: @11 = (-@11) */
  w11 = (- w11 );
  /* #151: (@0[2] += @11) */
  for (rr=w00+2, cs=(&w11); rr!=w00+3; rr+=1) *rr += *cs++;
  /* #152: @11 = (@8*@20) */
  w11  = (w08*w20);
  /* #153: @11 = (-@11) */
  w11 = (- w11 );
  /* #154: (@0[4] += @11) */
  for (rr=w00+4, cs=(&w11); rr!=w00+5; rr+=1) *rr += *cs++;
  /* #155: @13 = (@13*@20) */
  w13 *= w20;
  /* #156: @8 = (@8*@13) */
  w08 *= w13;
  /* #157: @8 = (-@8) */
  w08 = (- w08 );
  /* #158: (@0[2] += @8) */
  for (rr=w00+2, cs=(&w08); rr!=w00+3; rr+=1) *rr += *cs++;
  /* #159: @22 = (@22*@20) */
  w22 *= w20;
  /* #160: (@0[3] += @22) */
  for (rr=w00+3, cs=(&w22); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #161: output[0][0] = @0 */
  casadi_copy(w00, 8, res[0]);
  /* #162: @37 = zeros(2x1) */
  casadi_clear(w37, 2);
  /* #163: (@37[1] += @27) */
  for (rr=w37+1, cs=(&w27); rr!=w37+2; rr+=1) *rr += *cs++;
  /* #164: (@37[0] += @26) */
  for (rr=w37+0, cs=(&w26); rr!=w37+1; rr+=1) *rr += *cs++;
  /* #165: output[0][1] = @37 */
  if (res[0]) casadi_copy(w37, 2, res[0]+8);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 69;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 69*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
