/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenthfiala_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {11, 1, 1};

static const casadi_real casadi_zeros[10] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* f1tenthfiala_expl_ode_fun:(i0[10],i1[2],i2[11])->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, *w13=w+22, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  casadi_real *w24=w+37;
  const casadi_real *cs, *wr00;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[3] */
  w01 = wr00[3];
  /* #2: @2 = @0[2] */
  w02 = wr00[2];
  /* #3: @3 = cos(@2) */
  w03 = cos( w02 );
  /* #4: @4 = (@1*@3) */
  w04  = (w01*w03);
  /* #5: @5 = @0[4] */
  w05 = wr00[4];
  /* #6: @2 = sin(@2) */
  w02 = sin( w02 );
  /* #7: @6 = (@5*@2) */
  w06  = (w05*w02);
  /* #8: @4 = (@4-@6) */
  w04 -= w06;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #10: @2 = (@1*@2) */
  w02  = (w01*w02);
  /* #11: @3 = (@5*@3) */
  w03  = (w05*w03);
  /* #12: @2 = (@2+@3) */
  w02 += w03;
  /* #13: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #14: @2 = @0[5] */
  w02 = wr00[5];
  /* #15: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #16: @3 = 1e-09 */
  w03 = 1.0000000000000001e-09;
  /* #17: @4 = 0.17145 */
  w04 = 1.7144999999999999e-01;
  /* #18: @6 = (@4*@2) */
  w06  = (w04*w02);
  /* #19: @6 = (@6-@5) */
  w06 -= w05;
  /* #20: @7 = 0.1 */
  w07 = 1.0000000000000001e-01;
  /* #21: @8 = sq(@1) */
  w08 = casadi_sq( w01 );
  /* #22: @7 = (@7+@8) */
  w07 += w08;
  /* #23: @7 = sqrt(@7) */
  w07 = sqrt( w07 );
  /* #24: @6 = atan2(@6,@7) */
  w06  = atan2(w06,w07);
  /* #25: @6 = tan(@6) */
  w06 = tan( w06 );
  /* #26: @8 = sq(@6) */
  w08 = casadi_sq( w06 );
  /* #27: @9 = 0.051 */
  w09 = 5.0999999999999997e-02;
  /* #28: @10 = @0[6] */
  w10 = wr00[6];
  /* #29: @10 = (@9*@10) */
  w10  = (w09*w10);
  /* #30: @10 = (@10-@1) */
  w10 -= w01;
  /* #31: @10 = (@10/@7) */
  w10 /= w07;
  /* #32: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #33: @8 = (@8+@11) */
  w08 += w11;
  /* #34: @8 = (@3+@8) */
  w08  = (w03+w08);
  /* #35: @8 = sqrt(@8) */
  w08 = sqrt( w08 );
  /* #36: @12 = 3 */
  w12 = 3.;
  /* #37: @13 = input[2][0] */
  casadi_copy(arg[2], 5, w13);
  /* #38: @14 = @13[3] */
  for (rr=(&w14), cs=w13+3; cs!=w13+4; cs+=1) *rr++ = *cs;
  /* #39: @15 = 17.6391 */
  w15 = 1.7639134615384620e+01;
  /* #40: @16 = @0[7] */
  w16 = wr00[7];
  /* #41: @15 = (@15+@16) */
  w15 += w16;
  /* #42: @14 = (@14*@15) */
  w14 *= w15;
  /* #43: @17 = (@12*@14) */
  w17  = (w12*w14);
  /* #44: @18 = @13[1] */
  for (rr=(&w18), cs=w13+1; cs!=w13+2; cs+=1) *rr++ = *cs;
  /* #45: @19 = (@17/@18) */
  w19  = (w17/w18);
  /* #46: @19 = (@8<@19) */
  w19  = (w08<w19);
  /* #47: @18 = (@18*@8) */
  w18 *= w08;
  /* #48: @20 = sq(@18) */
  w20 = casadi_sq( w18 );
  /* #49: @20 = (@20/@17) */
  w20 /= w17;
  /* #50: @20 = (@18-@20) */
  w20  = (w18-w20);
  /* #51: @18 = pow(@18,@12) */
  w18  = pow(w18,w12);
  /* #52: @17 = 27 */
  w17 = 27.;
  /* #53: @21 = sq(@14) */
  w21 = casadi_sq( w14 );
  /* #54: @21 = (@17*@21) */
  w21  = (w17*w21);
  /* #55: @18 = (@18/@21) */
  w18 /= w21;
  /* #56: @20 = (@20+@18) */
  w20 += w18;
  /* #57: @20 = (@19?@20:0) */
  w20  = (w19?w20:0);
  /* #58: @19 = (!@19) */
  w19 = (! w19 );
  /* #59: @19 = (@19?@14:0) */
  w19  = (w19?w14:0);
  /* #60: @20 = (@20+@19) */
  w20 += w19;
  /* #61: @19 = (@20*@10) */
  w19  = (w20*w10);
  /* #62: @19 = (@19/@8) */
  w19 /= w08;
  /* #63: @14 = @13[4] */
  for (rr=(&w14), cs=w13+4; cs!=w13+5; cs+=1) *rr++ = *cs;
  /* #64: @14 = (@14*@15) */
  w14 *= w15;
  /* #65: @15 = (2.*@1) */
  w15 = (2.* w01 );
  /* #66: @15 = tanh(@15) */
  w15 = tanh( w15 );
  /* #67: @14 = (@14*@15) */
  w14 *= w15;
  /* #68: @19 = (@19-@14) */
  w19 -= w14;
  /* #69: @14 = @0[9] */
  w14 = wr00[9];
  /* #70: @15 = 0.15875 */
  w15 = 1.5875000000000000e-01;
  /* #71: @18 = (@15*@2) */
  w18  = (w15*w02);
  /* #72: @18 = (@18+@5) */
  w18 += w05;
  /* #73: @18 = atan2(@18,@7) */
  w18  = atan2(w18,w07);
  /* #74: @18 = (@14-@18) */
  w18  = (w14-w18);
  /* #75: @18 = tan(@18) */
  w18 = tan( w18 );
  /* #76: @7 = sq(@18) */
  w07 = casadi_sq( w18 );
  /* #77: @7 = (@7+@11) */
  w07 += w11;
  /* #78: @3 = (@3+@7) */
  w03 += w07;
  /* #79: @3 = sqrt(@3) */
  w03 = sqrt( w03 );
  /* #80: @7 = @13[2] */
  for (rr=(&w07), cs=w13+2; cs!=w13+3; cs+=1) *rr++ = *cs;
  /* #81: @11 = 19.0503 */
  w11 = 1.9050265384615390e+01;
  /* #82: @11 = (@11-@16) */
  w11 -= w16;
  /* #83: @7 = (@7*@11) */
  w07 *= w11;
  /* #84: @11 = (@12*@7) */
  w11  = (w12*w07);
  /* #85: @21 = @13[0] */
  for (rr=(&w21), cs=w13+0; cs!=w13+1; cs+=1) *rr++ = *cs;
  /* #86: @22 = (@11/@21) */
  w22  = (w11/w21);
  /* #87: @22 = (@3<@22) */
  w22  = (w03<w22);
  /* #88: @21 = (@21*@3) */
  w21 *= w03;
  /* #89: @23 = sq(@21) */
  w23 = casadi_sq( w21 );
  /* #90: @23 = (@23/@11) */
  w23 /= w11;
  /* #91: @23 = (@21-@23) */
  w23  = (w21-w23);
  /* #92: @21 = pow(@21,@12) */
  w21  = pow(w21,w12);
  /* #93: @11 = sq(@7) */
  w11 = casadi_sq( w07 );
  /* #94: @17 = (@17*@11) */
  w17 *= w11;
  /* #95: @21 = (@21/@17) */
  w21 /= w17;
  /* #96: @23 = (@23+@21) */
  w23 += w21;
  /* #97: @23 = (@22?@23:0) */
  w23  = (w22?w23:0);
  /* #98: @22 = (!@22) */
  w22 = (! w22 );
  /* #99: @22 = (@22?@7:0) */
  w22  = (w22?w07:0);
  /* #100: @23 = (@23+@22) */
  w23 += w22;
  /* #101: @10 = (@23*@10) */
  w10  = (w23*w10);
  /* #102: @10 = (@10/@3) */
  w10 /= w03;
  /* #103: @22 = cos(@14) */
  w22 = cos( w14 );
  /* #104: @7 = (@10*@22) */
  w07  = (w10*w22);
  /* #105: @7 = (@19+@7) */
  w07  = (w19+w07);
  /* #106: @23 = (@23*@18) */
  w23 *= w18;
  /* #107: @23 = (@23/@3) */
  w23 /= w03;
  /* #108: @14 = sin(@14) */
  w14 = sin( w14 );
  /* #109: @3 = (@23*@14) */
  w03  = (w23*w14);
  /* #110: @7 = (@7+@3) */
  w07 += w03;
  /* #111: @3 = 3.74 */
  w03 = 3.7400000000000002e+00;
  /* #112: @18 = (@7/@3) */
  w18  = (w07/w03);
  /* #113: @5 = (@5*@2) */
  w05 *= w02;
  /* #114: @18 = (@18+@5) */
  w18 += w05;
  /* #115: output[0][3] = @18 */
  if (res[0]) res[0][3] = w18;
  /* #116: @23 = (@23*@22) */
  w23 *= w22;
  /* #117: @22 = (-@23) */
  w22 = (- w23 );
  /* #118: @20 = (@20*@6) */
  w20 *= w06;
  /* #119: @20 = (@20/@8) */
  w20 /= w08;
  /* #120: @22 = (@22-@20) */
  w22 -= w20;
  /* #121: @14 = (@10*@14) */
  w14  = (w10*w14);
  /* #122: @22 = (@22+@14) */
  w22 += w14;
  /* #123: @22 = (@22/@3) */
  w22 /= w03;
  /* #124: @1 = (@1*@2) */
  w01 *= w02;
  /* #125: @22 = (@22-@1) */
  w22 -= w01;
  /* #126: output[0][4] = @22 */
  if (res[0]) res[0][4] = w22;
  /* #127: @14 = (@14-@23) */
  w14 -= w23;
  /* #128: @15 = (@15*@14) */
  w15 *= w14;
  /* #129: @4 = (@4*@20) */
  w04 *= w20;
  /* #130: @15 = (@15+@4) */
  w15 += w04;
  /* #131: @4 = 0.04712 */
  w04 = 4.7120000000000002e-02;
  /* #132: @15 = (@15/@4) */
  w15 /= w04;
  /* #133: output[0][5] = @15 */
  if (res[0]) res[0][5] = w15;
  /* #134: @15 = @0[8] */
  w15 = wr00[8];
  /* #135: @12 = (@12*@15) */
  w12 *= w15;
  /* #136: @19 = (@9*@19) */
  w19  = (w09*w19);
  /* #137: @12 = (@12-@19) */
  w12 -= w19;
  /* #138: @9 = (@9*@10) */
  w09 *= w10;
  /* #139: @12 = (@12-@9) */
  w12 -= w09;
  /* #140: @9 = 0.00016641 */
  w09 = 1.6641000000000000e-04;
  /* #141: @12 = (@12/@9) */
  w12 /= w09;
  /* #142: output[0][6] = @12 */
  if (res[0]) res[0][6] = w12;
  /* #143: @12 = -20 */
  w12 = -20.;
  /* #144: @9 = 0.224107 */
  w09 = 2.2410660205935795e-01;
  /* #145: @9 = (@9*@7) */
  w09 *= w07;
  /* #146: @16 = (@16-@9) */
  w16 -= w09;
  /* #147: @12 = (@12*@16) */
  w12 *= w16;
  /* #148: output[0][7] = @12 */
  if (res[0]) res[0][7] = w12;
  /* #149: @24 = input[1][0] */
  casadi_copy(arg[1], 2, w24);
  /* #150: @12 = @24[0] */
  for (rr=(&w12), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #151: output[0][8] = @12 */
  if (res[0]) res[0][8] = w12;
  /* #152: @12 = @24[1] */
  for (rr=(&w12), cs=w24+1; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #153: output[0][9] = @12 */
  if (res[0]) res[0][9] = w12;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenthfiala_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int f1tenthfiala_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenthfiala_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenthfiala_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenthfiala_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenthfiala_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenthfiala_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 39;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 39*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
